set(PROJECT_ACTION_CREATE "create")
set(PROJECT_ACTION_REMOVE "remove")

set(PROJECT_TYPE_LIBRARY "lib")
set(PROJECT_TYPE_APPLICATION "app")
set(PROJECT_TYPE_LIBRARY_DEPENDENCY "lib_dependency")
set(PROJECT_TYPE_APPLICATION_DEPENDENCY "app_dependency")

set(PROJECT_LIBRARY_ROOT "libs")
set(PROJECT_APPLICATION_ROOT "apps")
set(PROJECT_TEST_ROOT "tests")

set(PROJECT_TEST_FRAMEWORK_TARGET "utest_framework")
set(PROJECT_TEST_FRAMEWORK_SMOKE_TEST "utest_framework_smoke")
set(PROJECT_TEST_FRAMEWORK_HEADER "utest.hpp")
