function(project_fail message_text)
  message(FATAL_ERROR "${message_text}")
endfunction()

function(project_require_dependencies dependencies)
  if("${dependencies}" STREQUAL "")
    project_fail("Missing dependency name.")
  endif()
endfunction()

function(project_require_no_dependencies dependencies)
  if(NOT "${dependencies}" STREQUAL "")
    project_fail("This action does not accept dependencies.")
  endif()
endfunction()

function(project_validate_name name)
  if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$")
    project_fail("Invalid name: ${name}. Use a valid C++ namespace-like name, for example my_library.")
  endif()
endfunction()

function(project_validate_names names)
  foreach(name ${names})
    project_validate_name("${name}")
  endforeach()
endfunction()

function(project_require_path_exists path error_message)
  if(NOT EXISTS "${path}")
    project_fail("${error_message}: ${path}")
  endif()
endfunction()

function(project_require_path_does_not_exist path error_message)
  if(EXISTS "${path}")
    project_fail("${error_message}: ${path}")
  endif()
endfunction()